---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud.bigops.com.cn
  resources:
  - ingressmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.bigops.com.cn
  resources:
  - ingressmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.bigops.com.cn
  resources:
  - ingressmanagers/status
  verbs:
  - get
  - patch
  - update
